//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nextmeet.NextMeetDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan HoraInicio { get; set; }
        public System.TimeSpan HoraFin { get; set; }
        public string TipoHabitacion { get; set; }
        public string Complementos { get; set; }
        public decimal PrecioTotal { get; set; }
        public string ClienteNombre { get; set; }
        public string ClienteCorreo { get; set; }
    }
}
